In [11]:
import pandas as pd

In [12]:
df_dengue = pd.read_csv("data/dengue_data.csv")

In [13]:
df_dengue

,departamento,provincia,distrito,enfermedad,ano,semana,diagnostic,tipo_dx,diresa,ubigeo,edad,tipo_edad,sexo
0,HUANUCO,LEONCIO PRADO,LUYANDO,DENGUE SIN SIGNOS DE ALARMA,2000,47,A97.0,P,10.0,100605,9,A,M
1,HUANUCO,LEONCIO PRADO,LUYANDO,DENGUE SIN SIGNOS DE ALARMA,2000,40,A97.0,P,10.0,100605,18,A,F
2,HUANUCO,LEONCIO PRADO,JOSE CRESPO Y CASTILLO,DENGUE SIN SIGNOS DE ALARMA,2000,48,A97.0,C,10.0,100604,32,A,F
3,HUANUCO,LEONCIO PRADO,JOSE CRESPO Y CASTILLO,DENGUE SIN SIGNOS DE ALARMA,2000,37,A97.0,P,10.0,100604,40,A,F
4,HUANUCO,LEONCIO PRADO,MARIANO DAMASO BERAUN,DENGUE SIN SIGNOS DE ALARMA,2000,42,A97.0,C,10.0,100606,16,A,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...
757885,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,8,A,F
757886,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,C,24.0,240101,7,A,M
757887,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,6,A,M
757888,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,11,A,M
757889,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,C,24.0,240101,11,A,M

In [4]:
#Filtrar años 2021, 2022 y 2023
df_dengue = df_dengue[df_dengue["ano"].isin([2021,2022,2023])]
df_dengue

,departamento,provincia,distrito,enfermedad,ano,semana,diagnostic,tipo_dx,diresa,ubigeo,edad,tipo_edad,sexo
393242,CUSCO,LA CONVENCION,KIMBIRI,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,8.0,80907,23,A,M
393243,CAJAMARCA,JAEN,JAEN,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,38.0,60801,38,A,F
393244,JUNIN,CHANCHAMAYO,CHANCHAMAYO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120301,33,A,F
393245,JUNIN,CHANCHAMAYO,SAN LUIS DE SHUARO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120304,3,A,F
393246,JUNIN,CHANCHAMAYO,SAN LUIS DE SHUARO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120304,64,A,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...
757885,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,8,A,F
757886,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,C,24.0,240101,7,A,M
757887,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,6,A,M
757888,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,11,A,M
757889,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,C,24.0,240101,11,A,M

In [5]:
#Convertir todos los tipos de edad a años
from utils import convertir_a_anios
df_dengue.loc[:, ["edad_anios"]] = df_dengue.apply(convertir_a_anios, axis=1)
df_dengue

,departamento,provincia,distrito,enfermedad,ano,semana,diagnostic,tipo_dx,diresa,ubigeo,edad,tipo_edad,sexo,edad_anios
393242,CUSCO,LA CONVENCION,KIMBIRI,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,8.0,80907,23,A,M,23.0
393243,CAJAMARCA,JAEN,JAEN,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,38.0,60801,38,A,F,38.0
393244,JUNIN,CHANCHAMAYO,CHANCHAMAYO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120301,33,A,F,33.0
393245,JUNIN,CHANCHAMAYO,SAN LUIS DE SHUARO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120304,3,A,F,3.0
393246,JUNIN,CHANCHAMAYO,SAN LUIS DE SHUARO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120304,64,A,M,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757885,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,8,A,F,8.0
757886,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,C,24.0,240101,7,A,M,7.0
757887,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,6,A,M,6.0
757888,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,11,A,M,11.0
757889,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,C,24.0,240101,11,A,M,11.0

In [6]:
#Filtrar a menores de 13 años
df_dengue = df_dengue[df_dengue['edad_anios'] < 13]
df_dengue

,departamento,provincia,distrito,enfermedad,ano,semana,diagnostic,tipo_dx,diresa,ubigeo,edad,tipo_edad,sexo,edad_anios
393245,JUNIN,CHANCHAMAYO,SAN LUIS DE SHUARO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120304,3,A,F,3.0
393260,LORETO,LORETO,URARINAS,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,16.0,160305,1,A,F,1.0
393266,JUNIN,CHANCHAMAYO,CHANCHAMAYO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120301,10,A,F,10.0
393267,JUNIN,CHANCHAMAYO,PERENE,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120302,11,A,F,11.0
393272,JUNIN,SATIPO,RIO TAMBO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120608,9,A,F,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757885,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,8,A,F,8.0
757886,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,C,24.0,240101,7,A,M,7.0
757887,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,6,A,M,6.0
757888,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,11,A,M,11.0
757889,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,C,24.0,240101,11,A,M,11.0

In [7]:
#Clasificar grupo de edad
#Menor a 1 año: Bebé
#Menor a 5 años: Pequeño
#Entre 5 y 12 años: Mayor
from utils import clasificar_grupo_edad
df_dengue.loc[:, ["grupo_edad"]] = df_dengue["edad_anios"].apply(clasificar_grupo_edad)
df_dengue

,departamento,provincia,distrito,enfermedad,ano,semana,diagnostic,tipo_dx,diresa,ubigeo,edad,tipo_edad,sexo,edad_anios,grupo_edad
393245,JUNIN,CHANCHAMAYO,SAN LUIS DE SHUARO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120304,3,A,F,3.0,pequeño
393260,LORETO,LORETO,URARINAS,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,16.0,160305,1,A,F,1.0,pequeño
393266,JUNIN,CHANCHAMAYO,CHANCHAMAYO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120301,10,A,F,10.0,mayor
393267,JUNIN,CHANCHAMAYO,PERENE,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120302,11,A,F,11.0,mayor
393272,JUNIN,SATIPO,RIO TAMBO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120608,9,A,F,9.0,mayor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757885,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,8,A,F,8.0,mayor
757886,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,C,24.0,240101,7,A,M,7.0,mayor
757887,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,6,A,M,6.0,mayor
757888,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,11,A,M,11.0,mayor
757889,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,C,24.0,240101,11,A,M,11.0,mayor

In [ ]:
#Cargar nuestro archivo de coordenadas
df_coordenadas = pd.read_csv("data/distritos_peru.csv")
#Extraer columnas Latitud y Longitud
df_coordenadas[["latitud", "longitud"]] = df_coordenadas["Geo Point"].str.split(",", expand=True)
#Convertir coordenadas a float
df_coordenadas["latitud"] = df_coordenadas["latitud"].astype(float)
df_coordenadas["longitud"] = df_coordenadas["longitud"].astype(float)
#Realizaremos el merge con datos
df_dengue = df_dengue.merge(
    df_coordenadas,
    left_on=["ubigeo"],
    right_on=["UBIGEO"],
    how="left"
)
df_dengue

,departamento,provincia,distrito,enfermedad,ano,semana,diagnostic,tipo_dx,diresa,ubigeo,edad,tipo_edad,sexo,edad_anios,grupo_edad,Geo Point,UBIGEO,latitud,longitud
0,JUNIN,CHANCHAMAYO,SAN LUIS DE SHUARO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120304,3,A,F,3.0,pequeño,"-10.8432802591, -75.2727668878",120304,-10.843280,-75.272767
1,LORETO,LORETO,URARINAS,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,16.0,160305,1,A,F,1.0,pequeño,"-4.27492211676, -75.4846662463",160305,-4.274922,-75.484666
2,JUNIN,CHANCHAMAYO,CHANCHAMAYO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120301,10,A,F,10.0,mayor,"-11.0327769775, -75.3564454947",120301,-11.032777,-75.356445
3,JUNIN,CHANCHAMAYO,PERENE,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120302,11,A,F,11.0,mayor,"-10.9402818498, -75.075958845",120302,-10.940282,-75.075959
4,JUNIN,SATIPO,RIO TAMBO,DENGUE SIN SIGNOS DE ALARMA,2021,1,A97.0,C,12.0,120608,9,A,F,9.0,mayor,"-11.5310047922, -73.8144352005",120608,-11.531005,-73.814435
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68649,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,8,A,F,8.0,mayor,"-3.55366064722, -80.4161727295",240101,-3.553661,-80.416173
68650,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,C,24.0,240101,7,A,M,7.0,mayor,"-3.55366064722, -80.4161727295",240101,-3.553661,-80.416173
68651,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,6,A,M,6.0,mayor,"-3.55366064722, -80.4161727295",240101,-3.553661,-80.416173
68652,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,P,24.0,240101,11,A,M,11.0,mayor,"-3.55366064722, -80.4161727295",240101,-3.553661,-80.416173
68653,TUMBES,TUMBES,TUMBES,DENGUE SIN SIGNOS DE ALARMA,2023,52,A97.0,C,24.0,240101,11,A,M,11.0,mayor,"-3.55366064722, -80.4161727295",240101,-3.553661,-80.416173

In [ ]:
#Filtrar columnas a guardar
#Filtrar columnas a guardar
df_dengue = df_dengue[["departamento", "provincia", "distrito", "ubigeo", "latitud","longitud", "enfermedad", "ano", "tipo_dx", "edad_anios", "grupo_edad", "sexo"]]
#Guardar archivo
df_dengue.to_csv("data/dengue_ninos.csv", index=False)

df_dengue

,departamento,provincia,distrito,ubigeo,latitud,longitud,enfermedad,ano,tipo_dx,edad_anios,grupo_edad,sexo
0,JUNIN,CHANCHAMAYO,SAN LUIS DE SHUARO,120304,-10.843280,-75.272767,DENGUE SIN SIGNOS DE ALARMA,2021,C,3.0,pequeño,F
1,LORETO,LORETO,URARINAS,160305,-4.274922,-75.484666,DENGUE SIN SIGNOS DE ALARMA,2021,C,1.0,pequeño,F
2,JUNIN,CHANCHAMAYO,CHANCHAMAYO,120301,-11.032777,-75.356445,DENGUE SIN SIGNOS DE ALARMA,2021,C,10.0,mayor,F
3,JUNIN,CHANCHAMAYO,PERENE,120302,-10.940282,-75.075959,DENGUE SIN SIGNOS DE ALARMA,2021,C,11.0,mayor,F
4,JUNIN,SATIPO,RIO TAMBO,120608,-11.531005,-73.814435,DENGUE SIN SIGNOS DE ALARMA,2021,C,9.0,mayor,F
...,...,...,...,...,...,...,...,...,...,...,...,...
68649,TUMBES,TUMBES,TUMBES,240101,-3.553661,-80.416173,DENGUE SIN SIGNOS DE ALARMA,2023,P,8.0,mayor,F
68650,TUMBES,TUMBES,TUMBES,240101,-3.553661,-80.416173,DENGUE SIN SIGNOS DE ALARMA,2023,C,7.0,mayor,M
68651,TUMBES,TUMBES,TUMBES,240101,-3.553661,-80.416173,DENGUE SIN SIGNOS DE ALARMA,2023,P,6.0,mayor,M
68652,TUMBES,TUMBES,TUMBES,240101,-3.553661,-80.416173,DENGUE SIN SIGNOS DE ALARMA,2023,P,11.0,mayor,M
68653,TUMBES,TUMBES,TUMBES,240101,-3.553661,-80.416173,DENGUE SIN SIGNOS DE ALARMA,2023,C,11.0,mayor,M

In [ ]:
#Convertir nuestro csv a geoJSON
from utils import csv_a_geojson
csv_a_geojson('data/dengue_ninos.csv', 'data/dengue_geojson.json')